import i1 from "@public/img1.webp";
import i2 from "@public/img2.jpg";
import i3 from "@public/img3.jpg";
import i4 from "@public/img4.jpg";
import i5 from "@public/img5.jpg";
import i6 from "@public/img6.jpg";
import i7 from "@public/img7.webp";
import i8 from "@public/img8.jpg";
import i9 from "@public/img9.webp";
import i10 from "@public/img10.webp";
import i11 from "@public/img11.webp";
import i12 from "@public/img12.png";
import i13 from "@public/img13.jpg";
export const item = [
  {
    id: 1,
    image: i1,
    text: "Designer Pooja Set",
    ActualPrice: 499,
    DiscountProce: 200,
    value: 399,
    type: "garlands",
    typeOf: "Garlands",
  },
  {
    id: 2,
    image: i2,
    text: "Four cup panchwala",
    ActualPrice: 679,
    DiscountProce: 130,
    value: 549,
    type: "brass-gifts",
    typeOf: "Brass Gifts",
  },
  {
    id: 3,
    image: i3,
    text: "Brindavan Tulasi big",
    ActualPrice: 799,
    DiscountProce: 69,
    value: 730,
    type: "wedding-trays",
    typeOf: "Wedding Trays",
  },
  {
    id: 4,
    image: i4,
    text: "Ram Paivar Gift Box",
    ActualPrice: 489,
    DiscountProce: 60,
    value: 429,
    type: "home-decor",
    typeOf: "Home Decor",
  },
  {
    id: 5,
    image: i5,
    text: "Nakkas Dabbi",
    ActualPrice: 219,
    DiscountProce: 30,
    value: 189,
    type: "garlands",
    typeOf: "Garlands",
  },
  {
    id: 6,
    image: i6,
    text: "Round Silver Plate",
    ActualPrice: 999,
    DiscountProce: 40,
    value: 959,
    type: "silver-frames",
    typeOf: "999 Silver Frames",
  },
  {
    id: 7,
    image: i7,
    text: "GS Flowers pair",
    ActualPrice: 359,
    DiscountProce: 70,
    value: 289,
    type: "pooja-utilities",
    typeOf: "Pooja Utilities",
  },
  {
    id: 8,
    image: i8,
    text: "Hexagon Dabbi",
    ActualPrice: 459,
    DiscountProce: 100,
    value: 359,
    type: "return-gifts",
    typeOf: "Return Gifts",
  },
  {
    id: 9,
    image: i9,
    text: "Dry Fruit Fiber Box",
    ActualPrice: 399,
    DiscountProce: 100,
    value: 299,
    type: "combos",
    typeOf: "Combos",
  },
  {
    id: 10,
    image: i10,
    text: "Elephant Silver Pair",
    ActualPrice: 499,
    DiscountProce: 50,
    value: 459,
    type: "home-decor",
    typeOf: "Home Decor",
  },
  {
    id: 11,
    image: i11,
    text: "Astalakshmi Chembu",
    ActualPrice: 899,
    DiscountProce: 100,
    value: 799,
    type: "garlands",
    typeOf: "Garlands",
  },
  {
    id: 12,
    image: i12,
    text: "GS Lakshmi Face",
    ActualPrice: 1199,
    DiscountProce: 300,
    value: 899,
    type: "brass-gifts",
    typeOf: "Brass Gifts",
  },
  {
    id: 13,
    image: i13,
    text: "Baby Krishna Blue",
    ActualPrice: 399,
    DiscountProce: 100,
    value: 299,
    type: "new-arrivals-today",
    typeOf: "New Arrivals Today",
  },
  {
    id: 14,
    image: i1,
    text: "Imported Pooja Plate",
    ActualPrice: 989,
    DiscountProce: 200,
    value: 789,
    type: "gifts-under-200",
    typeOf: "Gifts Under 200",
  },
  {
    id: 15,
    image: i2,
    text: "Cow & Calf Silver Big",
    ActualPrice: 789,
    DiscountProce: 100,
    value: 689,
    type: "gifts-under-500",
    typeOf: "Gifts Under 500",
  },
  {
    id: 16,
    image: i3,
    text: "Mini Kalasha",
    ActualPrice: 549,
    DiscountProce: 200,
    value: 349,
    type: "garlands",
    typeOf: "Garlands",
  },
];
