export const orders = [
  {
    id: 1,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Paid",
    status: "unfulfilled",
    amount: "$200",
  },
  {
    id: 2,
    name: "Vest Hoddi",
    date: "Apr 14, 2022",
    customerName: "Jack",
    payment: "Unpaid",
    status: "Shipping",
    amount: "$200",
  },
  {
    id: 3,
    name: "Vest Hoddi",
    date: "Apr 14, 2022",
    customerName: "Jack",
    payment: "Paid",
    status: "unfulfilled",
    amount: "$200",
  },
  {
    id: 4,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Unpaid",
    status: "Shipping",
    amount: "$200",
  },
  {
    id: 5,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Paid",
    status: "unfulfilled",
    amount: "$200",
  },
  {
    id: 6,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Paid",
    status: "Shipping",
    amount: "$200",
  },
  {
    id: 7,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Unpaid",
    status: "unfulfilled",
    amount: "$200",
  },
  {
    id: 8,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Paid",
    status: "unfulfilled",
    amount: "$200",
  },
  {
    id: 9,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Unpaid",
    status: "Shipping",
    amount: "$200",
  },
  {
    id: 10,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Paid",
    status: "unfulfilled",
    amount: "$200",
  },
  {
    id: 11,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Unpaid",
    status: "Shipping",
    amount: "$200",
  },
  {
    id: 12,
    name: "Vest Hoddi",
    date: "Apr 24, 2022",
    customerName: "Jack",
    payment: "Paid",
    status: "unfulfilled",
    amount: "$200",
  },
];
